# /// script
# requires-python = ">=3.12"
# dependencies = ["psycopg[binary]>=3.2,<4"]
# ///

"""Create and populate the synthetic urban-mobility Postgres demo dataset."""

from __future__ import annotations

import argparse
import math
import os
import random
from collections import Counter, defaultdict
from datetime import UTC, date, datetime, time, timedelta

import psycopg
from psycopg import sql

SCHEMA = "metro_move"
SEED = 20260902
START_DATE = date(2025, 1, 1)
DAY_COUNT = 365
TABLES = (
    "dataset_metadata",
    "neighborhoods",
    "stations",
    "vehicles",
    "riders",
    "weather_hourly",
    "trips",
    "maintenance_events",
)

NEIGHBORHOODS = [
    (1, "Cedar Heights", "residential"),
    (2, "Maple Gardens", "residential"),
    (3, "North Commons", "residential"),
    (4, "Central Exchange", "business"),
    (5, "Market Quarter", "business"),
    (6, "Innovation District", "business"),
    (7, "Harbor Point", "leisure"),
    (8, "Museum Row", "leisure"),
    (9, "Riverwalk", "leisure"),
    (10, "Summit Campus", "education"),
]

SCHEMA_SQL = """
CREATE SCHEMA metro_move;
COMMENT ON SCHEMA metro_move IS
  'Fictional synthetic urban-mobility data generated by Easy Query. No real people, trips, or organizations are represented.';

CREATE TABLE metro_move.dataset_metadata (
  key text PRIMARY KEY,
  value text NOT NULL
);
CREATE TABLE metro_move.neighborhoods (
  neighborhood_id smallint PRIMARY KEY,
  name text NOT NULL UNIQUE,
  district_type text NOT NULL CHECK (district_type IN ('residential', 'business', 'leisure', 'education'))
);
CREATE TABLE metro_move.stations (
  station_id integer PRIMARY KEY,
  name text NOT NULL UNIQUE,
  neighborhood_id smallint NOT NULL REFERENCES metro_move.neighborhoods,
  station_type text NOT NULL CHECK (station_type IN ('street', 'transit_hub', 'park', 'campus')),
  capacity smallint NOT NULL CHECK (capacity > 0),
  latitude numeric(8, 5) NOT NULL,
  longitude numeric(8, 5) NOT NULL,
  opened_on date NOT NULL
);
CREATE TABLE metro_move.vehicles (
  vehicle_id integer PRIMARY KEY,
  vehicle_code text NOT NULL UNIQUE,
  vehicle_type text NOT NULL CHECK (vehicle_type IN ('bike', 'e-bike', 'scooter')),
  model text NOT NULL,
  commissioned_on date NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'maintenance', 'retired'))
);
CREATE TABLE metro_move.riders (
  rider_id integer PRIMARY KEY,
  rider_code text NOT NULL UNIQUE,
  membership_type text NOT NULL CHECK (membership_type IN ('annual', 'monthly', 'day_pass')),
  signup_date date NOT NULL,
  home_neighborhood_id smallint REFERENCES metro_move.neighborhoods,
  age_group text NOT NULL CHECK (age_group IN ('18-24', '25-34', '35-44', '45-54', '55+'))
);
CREATE TABLE metro_move.weather_hourly (
  observed_at timestamptz PRIMARY KEY,
  temperature_c numeric(4, 1) NOT NULL,
  precipitation_mm numeric(5, 1) NOT NULL CHECK (precipitation_mm >= 0),
  wind_kph numeric(4, 1) NOT NULL CHECK (wind_kph >= 0),
  conditions text NOT NULL CHECK (conditions IN ('clear', 'cloudy', 'rain', 'snow'))
);
CREATE TABLE metro_move.trips (
  trip_id bigint PRIMARY KEY,
  started_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  start_station_id integer NOT NULL REFERENCES metro_move.stations,
  end_station_id integer NOT NULL REFERENCES metro_move.stations,
  vehicle_id integer NOT NULL REFERENCES metro_move.vehicles,
  rider_id integer NOT NULL REFERENCES metro_move.riders,
  distance_km numeric(5, 2) NOT NULL CHECK (distance_km > 0),
  duration_minutes smallint NOT NULL CHECK (duration_minutes > 0),
  fare_usd numeric(6, 2) NOT NULL CHECK (fare_usd >= 0),
  CHECK (ended_at > started_at),
  CHECK (start_station_id <> end_station_id)
);
CREATE TABLE metro_move.maintenance_events (
  event_id bigint PRIMARY KEY,
  vehicle_id integer NOT NULL REFERENCES metro_move.vehicles,
  reported_at timestamptz NOT NULL,
  resolved_at timestamptz NOT NULL,
  issue_type text NOT NULL CHECK (issue_type IN ('brakes', 'battery', 'tire', 'electronics', 'frame')),
  severity text NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
  repair_cost_usd numeric(7, 2) NOT NULL CHECK (repair_cost_usd >= 0),
  CHECK (resolved_at > reported_at)
);

CREATE INDEX trips_started_at_idx ON metro_move.trips (started_at);
CREATE INDEX trips_start_station_idx ON metro_move.trips (start_station_id);
CREATE INDEX trips_end_station_idx ON metro_move.trips (end_station_id);
CREATE INDEX trips_vehicle_idx ON metro_move.trips (vehicle_id);
CREATE INDEX trips_rider_idx ON metro_move.trips (rider_id);
CREATE INDEX maintenance_vehicle_idx ON metro_move.maintenance_events (vehicle_id, reported_at);

COMMENT ON TABLE metro_move.riders IS
  'Synthetic rider profiles. rider_code is fictional and no names, emails, addresses, or other personal data are stored.';
COMMENT ON TABLE metro_move.trips IS
  'Synthetic trips for calendar year 2025 with deliberately seeded commute, weather, weekend, and seasonal patterns.';
COMMENT ON TABLE metro_move.weather_hourly IS
  'Entirely synthetic hourly weather used to make cross-table analysis possible.';
"""


def build_data() -> dict[str, list[tuple[object, ...]]]:
    rng = random.Random(SEED)

    stations: list[tuple[object, ...]] = []
    station_ids_by_type: dict[str, list[int]] = defaultdict(list)
    suffixes = ("Center", "North", "East", "South", "West", "Plaza")
    station_id = 1
    for neighborhood_id, name, district_type in NEIGHBORHOODS:
        for offset, suffix in enumerate(suffixes):
            station_type = {
                "residential": "street",
                "business": "transit_hub",
                "leisure": "park",
                "education": "campus",
            }[district_type]
            stations.append(
                (
                    station_id,
                    f"{name} {suffix}",
                    neighborhood_id,
                    station_type,
                    rng.randrange(18, 53),
                    round(40.0 + neighborhood_id * 0.012 + offset * 0.0017, 5),
                    round(-74.0 + neighborhood_id * 0.009 - offset * 0.0013, 5),
                    date(2018, 1, 1) + timedelta(days=rng.randrange(0, 2_100)),
                )
            )
            station_ids_by_type[district_type].append(station_id)
            station_id += 1

    model_options = [
        ("bike", "Model-C1", 0.42),
        ("e-bike", "Model-E1", 0.28),
        ("e-bike", "Model-E2", 0.18),
        ("scooter", "Model-S1", 0.12),
    ]
    vehicles: list[tuple[object, ...]] = []
    vehicle_ids_by_type: dict[str, list[int]] = defaultdict(list)
    vehicle_model_by_id: dict[int, str] = {}
    for vehicle_id in range(1, 1_001):
        vehicle_type, model, _ = rng.choices(
            model_options, weights=[item[2] for item in model_options], k=1
        )[0]
        vehicles.append(
            (
                vehicle_id,
                f"MM-{vehicle_id:04d}",
                vehicle_type,
                model,
                date(2021, 1, 1) + timedelta(days=rng.randrange(0, 1_460)),
                "active",
            )
        )
        vehicle_ids_by_type[vehicle_type].append(vehicle_id)
        vehicle_model_by_id[vehicle_id] = model

    riders: list[tuple[object, ...]] = []
    rider_ids_by_membership: dict[str, list[int]] = defaultdict(list)
    for rider_id in range(1, 15_001):
        membership_type = rng.choices(
            ["annual", "monthly", "day_pass"], weights=[0.52, 0.28, 0.20], k=1
        )[0]
        riders.append(
            (
                rider_id,
                f"R-{rider_id:05d}",
                membership_type,
                date(2021, 1, 1) + timedelta(days=rng.randrange(0, 1_460)),
                rng.choice([item[0] for item in NEIGHBORHOODS]),
                rng.choices(
                    ["18-24", "25-34", "35-44", "45-54", "55+"],
                    weights=[0.17, 0.34, 0.25, 0.15, 0.09],
                    k=1,
                )[0],
            )
        )
        rider_ids_by_membership[membership_type].append(rider_id)

    weather: list[tuple[object, ...]] = []
    precipitation_by_day: dict[date, float] = {}
    for day_offset in range(DAY_COUNT):
        current_date = START_DATE + timedelta(days=day_offset)
        seasonal_temperature = 13 + 12 * math.sin(
            2 * math.pi * (day_offset - 105) / DAY_COUNT
        )
        rainy_day = rng.random() < (0.24 if current_date.month in {6, 7, 8} else 0.31)
        rain_start = rng.randrange(0, 18) if rainy_day else -1
        rain_length = rng.randrange(2, 9) if rainy_day else 0
        daily_precipitation = 0.0
        for hour in range(24):
            observed_at = datetime.combine(current_date, time(hour), tzinfo=UTC)
            temperature = (
                seasonal_temperature
                + 4 * math.sin(2 * math.pi * (hour - 8) / 24)
                + rng.uniform(-1.8, 1.8)
            )
            precipitation = (
                round(rng.uniform(0.4, 3.8), 1)
                if rain_start <= hour < rain_start + rain_length
                else 0.0
            )
            daily_precipitation += precipitation
            if precipitation and temperature < 1.5:
                conditions = "snow"
            elif precipitation:
                conditions = "rain"
            elif rng.random() < 0.38:
                conditions = "cloudy"
            else:
                conditions = "clear"
            weather.append(
                (
                    observed_at,
                    round(temperature, 1),
                    precipitation,
                    round(max(2.0, rng.gauss(13 if rainy_day else 9, 3.2)), 1),
                    conditions,
                )
            )
        precipitation_by_day[current_date] = daily_precipitation

    all_station_ids = [row[0] for row in stations]
    weekday_hours = [
        1,
        1,
        1,
        1,
        1,
        2,
        5,
        10,
        14,
        9,
        5,
        5,
        6,
        6,
        6,
        7,
        11,
        15,
        12,
        8,
        5,
        3,
        2,
        1,
    ]
    weekend_hours = [
        1,
        1,
        1,
        1,
        1,
        1,
        2,
        3,
        5,
        7,
        9,
        11,
        12,
        12,
        11,
        10,
        9,
        8,
        7,
        5,
        4,
        3,
        2,
        1,
    ]
    trips: list[tuple[object, ...]] = []
    trip_count_by_vehicle: Counter[int] = Counter()
    trip_id = 1
    for day_offset in range(DAY_COUNT):
        current_date = START_DATE + timedelta(days=day_offset)
        weekend = current_date.weekday() >= 5
        seasonal_factor = (
            0.78
            + 0.30 * (1 + math.sin(2 * math.pi * (day_offset - 105) / DAY_COUNT)) / 2
        )
        rain_factor = max(0.58, 1 - precipitation_by_day[current_date] / 45)
        festival_factor = (
            1.35 if date(2025, 8, 14) <= current_date <= date(2025, 8, 23) else 1.0
        )
        trips_today = round(
            300
            * seasonal_factor
            * rain_factor
            * (1.12 if weekend else 1.0)
            * festival_factor
        )
        for _ in range(trips_today):
            hour = rng.choices(
                range(24), weights=weekend_hours if weekend else weekday_hours, k=1
            )[0]
            if not weekend and 6 <= hour <= 9:
                start_pool = station_ids_by_type["residential"]
                end_pool = station_ids_by_type["business"]
            elif not weekend and 16 <= hour <= 19:
                start_pool = station_ids_by_type["business"]
                end_pool = station_ids_by_type["residential"]
            elif weekend and rng.random() < 0.58:
                start_pool = all_station_ids
                end_pool = station_ids_by_type["leisure"]
            else:
                start_pool = all_station_ids
                end_pool = all_station_ids
            start_station_id = rng.choice(start_pool)
            end_station_id = rng.choice(end_pool)
            while end_station_id == start_station_id:
                end_station_id = rng.choice(end_pool)

            raining = precipitation_by_day[current_date] > 3
            membership_type = rng.choices(
                ["annual", "monthly", "day_pass"],
                weights=[
                    0.57,
                    0.26,
                    (0.38 if weekend else 0.17) * (0.55 if raining else 1),
                ],
                k=1,
            )[0]
            rider_id = rng.choice(rider_ids_by_membership[membership_type])
            vehicle_type = rng.choices(
                ["bike", "e-bike", "scooter"],
                weights=[0.50, 0.42, 0.03 if raining else 0.14],
                k=1,
            )[0]
            vehicle_id = rng.choice(vehicle_ids_by_type[vehicle_type])
            trip_count_by_vehicle[vehicle_id] += 1

            distance_km = min(18.0, 0.35 + rng.gammavariate(2.2, 1.05))
            speed_kph = {"bike": 14.0, "e-bike": 19.0, "scooter": 16.0}[vehicle_type]
            duration = max(
                3, round(distance_km / speed_kph * 60 * rng.uniform(0.9, 1.25) + 2)
            )
            started_at = datetime.combine(
                current_date, time(hour), tzinfo=UTC
            ) + timedelta(minutes=rng.randrange(60), seconds=rng.randrange(60))
            base_fare, minute_rate = {
                "annual": (0.20, 0.08),
                "monthly": (0.50, 0.10),
                "day_pass": (2.50, 0.24),
            }[membership_type]
            trips.append(
                (
                    trip_id,
                    started_at,
                    started_at + timedelta(minutes=duration),
                    start_station_id,
                    end_station_id,
                    vehicle_id,
                    rider_id,
                    round(distance_km, 2),
                    duration,
                    round(base_fare + duration * minute_rate, 2),
                )
            )
            trip_id += 1

    maintenance_events: list[tuple[object, ...]] = []
    event_id = 1
    for vehicle_id, trip_count in sorted(trip_count_by_vehicle.items()):
        model = vehicle_model_by_id[vehicle_id]
        event_count = int(
            trip_count
            / 65
            * {"Model-C1": 0.85, "Model-E1": 1.05, "Model-E2": 1.85, "Model-S1": 1.25}[
                model
            ]
            + rng.random()
        )
        issue_weights = {
            "Model-C1": [0.36, 0.01, 0.42, 0.03, 0.18],
            "Model-E1": [0.24, 0.28, 0.24, 0.18, 0.06],
            "Model-E2": [0.18, 0.42, 0.16, 0.20, 0.04],
            "Model-S1": [0.24, 0.24, 0.30, 0.18, 0.04],
        }[model]
        for _ in range(event_count):
            issue = rng.choices(
                ["brakes", "battery", "tire", "electronics", "frame"],
                weights=issue_weights,
                k=1,
            )[0]
            severity = rng.choices(
                ["low", "medium", "high"], weights=[0.52, 0.36, 0.12], k=1
            )[0]
            reported_at = datetime(2025, 1, 1, tzinfo=UTC) + timedelta(
                minutes=rng.randrange(DAY_COUNT * 24 * 60)
            )
            repair_hours = {
                "low": rng.uniform(1, 6),
                "medium": rng.uniform(6, 24),
                "high": rng.uniform(24, 72),
            }[severity]
            issue_cost = {
                "brakes": 45,
                "battery": 180,
                "tire": 32,
                "electronics": 125,
                "frame": 210,
            }[issue]
            severity_factor = {"low": 0.75, "medium": 1.15, "high": 1.65}[severity]
            maintenance_events.append(
                (
                    event_id,
                    vehicle_id,
                    reported_at,
                    reported_at + timedelta(hours=repair_hours),
                    issue,
                    severity,
                    round(issue_cost * severity_factor * rng.uniform(0.85, 1.2), 2),
                )
            )
            event_id += 1

    return {
        "dataset_metadata": [
            ("dataset_name", "Synthetic Urban Mobility Demo"),
            ("dataset_version", "1"),
            ("description", "Fictional synthetic urban-mobility demo data"),
            ("generator_seed", str(SEED)),
            ("date_range", "2025-01-01 through 2025-12-31"),
            ("contains_real_people", "false"),
            ("uses_third_party_data", "false"),
        ],
        "neighborhoods": NEIGHBORHOODS,
        "stations": stations,
        "vehicles": vehicles,
        "riders": riders,
        "weather_hourly": weather,
        "trips": trips,
        "maintenance_events": maintenance_events,
    }


def copy_rows(
    cursor: psycopg.Cursor[tuple[object, ...]],
    table: str,
    columns: tuple[str, ...],
    rows: list[tuple[object, ...]],
) -> None:
    with cursor.copy(
        f"COPY {SCHEMA}.{table} ({', '.join(columns)}) FROM STDIN"
    ) as copy:
        for row in rows:
            copy.write_row(row)


def get_database_url() -> str:
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise SystemExit(
            "DATABASE_URL is not set. Run with: uv run --env-file .env.local scripts/metro_move/seed.py"
        )
    return database_url


def seed_database(data: dict[str, list[tuple[object, ...]]], reset: bool) -> None:
    with psycopg.connect(get_database_url(), connect_timeout=15) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = %s)",
                (SCHEMA,),
            )
            schema_exists = cursor.fetchone()[0]
            if schema_exists and not reset:
                raise SystemExit(
                    f"Schema {SCHEMA!r} already exists. Re-run with --reset to replace only that schema."
                )
            if schema_exists:
                cursor.execute("DROP SCHEMA metro_move CASCADE")
            cursor.execute(SCHEMA_SQL)

            specs = {
                "dataset_metadata": ("key", "value"),
                "neighborhoods": ("neighborhood_id", "name", "district_type"),
                "stations": (
                    "station_id",
                    "name",
                    "neighborhood_id",
                    "station_type",
                    "capacity",
                    "latitude",
                    "longitude",
                    "opened_on",
                ),
                "vehicles": (
                    "vehicle_id",
                    "vehicle_code",
                    "vehicle_type",
                    "model",
                    "commissioned_on",
                    "status",
                ),
                "riders": (
                    "rider_id",
                    "rider_code",
                    "membership_type",
                    "signup_date",
                    "home_neighborhood_id",
                    "age_group",
                ),
                "weather_hourly": (
                    "observed_at",
                    "temperature_c",
                    "precipitation_mm",
                    "wind_kph",
                    "conditions",
                ),
                "trips": (
                    "trip_id",
                    "started_at",
                    "ended_at",
                    "start_station_id",
                    "end_station_id",
                    "vehicle_id",
                    "rider_id",
                    "distance_km",
                    "duration_minutes",
                    "fare_usd",
                ),
                "maintenance_events": (
                    "event_id",
                    "vehicle_id",
                    "reported_at",
                    "resolved_at",
                    "issue_type",
                    "severity",
                    "repair_cost_usd",
                ),
            }
            for table, columns in specs.items():
                copy_rows(cursor, table, columns, data[table])

        print(
            f"Seeded {connection.info.dbname} on {connection.info.host} into schema {SCHEMA}."
        )


def verify_database() -> None:
    with (
        psycopg.connect(get_database_url(), connect_timeout=15) as connection,
        connection.cursor() as cursor,
    ):
        print("Database row counts:")
        for table in TABLES:
            cursor.execute(
                sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
                    sql.Identifier(SCHEMA), sql.Identifier(table)
                )
            )
            print(f"{table}: {cursor.fetchone()[0]:,} rows")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate the deterministic dataset and print row counts without connecting.",
    )
    mode.add_argument(
        "--verify-only",
        action="store_true",
        help="Read and print row counts from an existing metro_move schema.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Drop and replace only the metro_move schema if it already exists.",
    )
    args = parser.parse_args()

    if args.verify_only:
        verify_database()
        return

    data = build_data()
    for table, rows in data.items():
        print(f"{table}: {len(rows):,} rows")
    if not args.dry_run:
        seed_database(data, args.reset)
        verify_database()


if __name__ == "__main__":
    main()
